### ISSUE TITLE
after patching comment block disappeared

### ISSUE THREAD

**Issue by andreykyz** [krishicks/yaml-patch#16]
yaml with comment block:
```
---
foo: bar
#comment block1
baz:
  quux: grault #comment block2
```
After executing example from https://github.com/krishicks/yaml-patch#example

```
baz:
  quux: grault
  waldo: fred
foo: bar
```
