### ISSUE TITLE
insertion of an element into an array within array with a search directive fails

### ISSUE THREAD

**Issue by mevansam** [krishicks/yaml-patch#4]
Yaml-patch gives an error when attempting to insert an element with an array that is within another array.

Error:
```
2017/06/03 11:07:13 error applying patch: could not expand pointer: /jobs/name=upgrade-tile/plan/-
```

Op:
```
- op: add
  path: /jobs/name=upgrade-tile/plan/-
  value:
    put: pcf-env
    params:
      release: pcf-env
```

The following op works and achieves the same expected behavior as above
```
- op: add
  path: /jobs/1/plan/-
  value:
    put: pcf-env
    params:
      release: pcf-env
```
